local CloseNotifications = require('CloseNotifications')
local Caffeine = require('Caffeine')
local ReloadConfig = require('ReloadConfig')
-- local ConfigAutoLoad = require('ConfigAutoLoad')
-- local DoubleTapCmd = require('DoubleTapCmd')
-- local scratchpad = require('scratchpad')
